### ISSUE TITLE
Build with config

### ISSUE THREAD

**Issue by spyzhov** [spyzhov/goat#12]
prepare solution to build using config, like:
```yaml
repo: github.com/repo/name
services:
  - fast-http
  - mysql
  - rmq-consumer
```
